blank_issues_enabled: true
contact_links:
  - name: Feature Request
    url: https://github.com/zhw1nq/panel/discussions
    about: Suggest a new feature or improvement for the software.
  - name: Installation Help
    url: https://panel.zhw1nq.dev/discord
    about: Please visit our Discord for help with your installation.
  - name: General Question
    url: https://panel.zhw1nq.dev/discord
    about: Please visit our Discord for general questions about zSystems.
